#deploy
name: CICD for Youtube

on:
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node js
        uses: actions/setup-node@v3.6.0
        with:
         node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install
          npm run build

        env: 
          CI: true   


  depoly:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
     - name: SSH deploy
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.SSH_IP }}
          username:  ${{ secrets.SSH_USERNAME }}
          key:  ${{ secrets.SSH_KEY }}
          script: |
               apt-get update
               cd ~
               curl -sL https://deb.nodesource.com/setup_16.x -o /tmp/nodesource_setup.sh
               sudo bash /tmp/nodesource_setup.sh
               sudo apt install nodejs
               node -v
               npm install -g pm2
               cd /home/ubuntu
               git clone https://github.com/tawdebo/ci-cd-nodejs.git
               cd /home/ubuntu/ci-cd-nodejs
               npm install
               npm run build
               pm2 delete all
               pm2 restart app
               
            



