name: CICD for Youtube

on:
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node js
        uses: actions/setup-node@v3.6.0
        with:
         node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install
          npm run build

        env: 
          CI: true   


  depoly:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
     - name: SSH deploy
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.SSH_IP }}
          username:  ${{ secrets.SSH_USERNAME }}
          key:  ${{ secrets.SSH_KEY }}
          script: |
              curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
              . ~/.nvm/nvm.sh
               apt-get install node
               nvm instal 16
               npm install -g pm2
               cd ~/home/ubuntu
               git pull origin main
               npm install
               npm run build
               pm2 restart api
            



